### ISSUE TITLE
Error TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by iFanpS** [aresch/pyenet#24]
Traceback (most recent call last):
  File ".\testing.py", line 3, in <module>
    host = enet.Host(enet.Address("localhost", 8000), 1, 0, 0, 0)
  File "enet.pyx", line 262, in enet.Address.__init__
  File "enet.pyx", line 296, in enet.Address.host.__set__

**Comment by splexas** [comment]
expected bytes, that's supposed to be b"localhost"
